# Generated by Django 3.2.4 on 2021-06-10 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210610_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(default=datetime.datetime(2021, 6, 10, 17, 54, 26, 357902, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
