# Generated by Django 3.2.4 on 2021-06-11 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shop_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=datetime.datetime(2021, 6, 11, 17, 31, 36, 584029, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
