# Generated by Django 3.2.4 on 2021-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
