# Generated by Django 3.2.4 on 2021-06-16 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 3, 47, 27, 540357, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 3, 47, 39, 873751, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 3, 47, 57, 987465, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 3, 48, 10, 241755, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
