# Generated by Django 3.2.4 on 2021-06-16 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_require'),
    ]

    operations = [
        migrations.AlterField(
            model_name='require',
            name='customer',
            field=models.CharField(default=datetime.datetime(2021, 6, 16, 18, 52, 15, 304973, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
