# Generated by Django 3.2.4 on 2021-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210707_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
