# Generated by Django 3.2.4 on 2021-07-17 08:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0024_auto_20210709_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discripton',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=datetime.datetime(2021, 7, 17, 8, 54, 8, 413479, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
