# Generated by Django 3.2.4 on 2021-07-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210717_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='require',
            old_name='discripton',
            new_name='description',
        ),
    ]
