# Generated by Django 3.2.4 on 2021-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210717_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zipcode',
            field=models.IntegerField(max_length=6),
        ),
    ]
