# Generated by Django 3.2.4 on 2021-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20210731_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
