# Generated by Django 3.2.4 on 2021-08-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20210815_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ship'),
        ),
    ]
