# Generated by Django 3.2.4 on 2021-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_orderitem_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='out_for_delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
