# Generated by Django 3.2.4 on 2021-08-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_shippingaddress_out_for_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
