# Generated by Django 3.2.4 on 2021-08-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210815_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='out_for_delivery',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipped',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='out_for_delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
