# Generated by Django 3.2.4 on 2021-08-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20210815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.ship'),
        ),
    ]
